kieler/KLighD

plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/syntheses/ReinitializingDiagramSynthesisProxy.java
=> klighd: Make sure calling getDelegate() in ReinitializingDiagramSynthesisProxy always creates the instance first.

plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/nodes/KlighdStyledText.java
Hey guys, please give this change a try. I hope it improves diagram rendering performance significantly and does no harm.
=> klighd.piccolo: fixed performance waste in 'KlighdStyledText'

plugins/de.cau.cs.kieler.klighd.kgraph/src/de/cau/cs/kieler/klighd/kgraph/util/KGraphUtil.java, plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/controller/DiagramController.java, plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/controller/KLabelRenderingController.java, plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/nodes/KLabelNode.java, plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/nodes/KlighdStyledText.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/internal/macrolayout/KlighdDiagramLayoutConnector.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/util/KlighdProperties.java
* introduced guarding property 'MULTIPLE_KTEXTS_PER_KLABEL' preserving the existing behavior by default if not explicitly set to 'true'
* relaxed handling of label text, may now be specified within the first KText alternatively
* dropped dead code as discussed in #54
=> klighd +.piccolo: enabled support of multiple KTexts per KLabel as demanded in #43

plugins/de.cau.cs.kieler.klighd.krendering.extensions/src/de/cau/cs/kieler/klighd/krendering/extensions/KNodeExtensions.xtend, plugins/de.cau.cs.kieler.klighd.krendering.extensions/src/de/cau/cs/kieler/klighd/krendering/extensions/KPortExtensions.xtend
Added new method for KPort and KNode extensions to register nodes/ports that were not create with the create method but should be available via the getters.
=> New Method for KPort and KNode Extensions

plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/Klighd.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/ViewContext.java
Previously, any code calling `Klighd.handle(IStatus)` caused the status and possible warnings and exceptions within to not be shown anywhere. This alters that behavior, so that the status is at least logged, matching the default behavior of the previoulsy used Eclipse StatusManager's `handle(IStatus)` method.
Furthermore, this shows an exception being thrown during a synthesis to the user in addition to logging it, so that errors during syntheses can be tracked down more easily.
=> Changed default status handling to 'log', and show exceptions during synthesis transformations to the user.

plugins/de.cau.cs.kieler.klighd.ui.view/src/de/cau/cs/kieler/klighd/ui/view/DiagramView.java
In the Eclipse 2020-09 release the toolbar of the diagram view looses all its item as soon as an editor is switched. This commit fixes this issue.
However, the responsible code has the comment "_important for correct toolbar layout_". I guess I added it for a reason but I could not reproduce the problem that requires this line of code. Hence, in 2020-09 this line breaks the toolbar, in 2020-06 and 2020-03 this line makes no difference (tested) and probably in some previous release it was necessary.
I would say we want to have this bugfix anyway but you might want to check that it has no consequences for earlier releases that are important to you.
=> Disappearing Toolbar Items

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/gson_utils/EObjectSerializer.xtend, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/util/KlighdProperties.java
Adds property to KLighD that syntheses may use to indicate a text within renderings of a node to be the quasi-label of it to be displayed instead of the usual renderings in very zoomed out scenarios, as used for the browsing project in KEITH.
Same as #80, but with master as the goal and up to date changes that really happened in this PR.
=> Add node title property to KTexts

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramUpdater.xtend
During the LSP initialization process a client is able to specify persisted synthesis options. If no synthesis options are provided, the server currently throws (and catches) a `NullPointerException` "Could not load client-side synthesis options" and continues to generates a diagram with default synthesis options anyway.
However, a client is not always able to provide synthesis options, which makes the exception slightly irritating in such situations. For example, a KEITH Theia ide that is used for the first time or has cleared `localStorage` does not have persisted options.
This PR prevents the `NullPointException` by using an empty `synthesisOptions` object if necessary.
=> Fix missing synthesis options during LSP initialization throws a NullPointerException

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramGenerator.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramModule.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramState.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramUpdater.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/KeithDiagramSelectionListener.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/LazyTraceProvider.xtend
If the element trace on SModelElements is required for tracing from text
to the diagram or vice versa the traces are now generated lazily only
when they are needed. This speeds up the initial diagram generation
time, especially for very large graphs, where the
PositionConverter#toPosition has an O(n^2) runtime in the model size
because it runs through every character of the model for every model
element.
Tracing from diagram to text is now fast, text to diagram still goes
through the all traces and suffers from above mentioned bad runtime for
very large graphs.
Closes #57.
Closes #90.
=> lsp: switched to lazy tracing of diagram elements.

plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/internal/options/SynthesisOptionControlFactory.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/SynthesisOption.java
Closes #14 
Just a small change to allow to have a more descriptive text shown when hovering over synthesis options. Follows the behavior of hover feedback for layout options.
This is optional to set and therefore does not break existing API. If no description is set, the name of the option is shown as the tooltip instead.
=> Added possibility to configure descriptions for synthesis options and show them in tooltips on hover.

plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/nodes/KGraphElementNode.java, plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/nodes/KNodeAbstractNode.java, plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/nodes/KlighdDisposingLayer.java
… after turning (most of) the labels & ports invisible (#106)
change is a consequence of the altered implementation of 'IViewer.hide(...)' and 'IViewer.show(...)', see the changes in
f89b47b1dfbe2b2c199bc21bce0224f7ab467956
c5509a69b937d26746969b949287ed44c7a7c65a
e5685e9d4be14d5e23c8b24c710cde0f70385f86
f6c4a902d2c8d6e51a38c8695ef39ef6aaac561e
3fc43aff21bb66104e54e8019bccc49488118cd1
=> klighd.piccolo: fixes issue of missing updates of cached bounds on label and port layers

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramGenerator.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphIncrementalDiagramGenerator.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/model/KGraphModel.xtend
Server-side changes corresponding to these [client-side changes](https://github.com/kieler/klighd-vscode/pull/76)
Removes no longer required tooltip field from SKGraph model
=> remove unused tooltip field from skgraph field and corresponding references

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramServer.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/model/Actions.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/model/OptionMessageData.xtend, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/microlayout/PlacementUtil.java
This fixes two issues that were present when executing the Language Server on a system which has problems with calling SWT, for example on new Macs with M2 chips:
- removes the SWT image from being sent to klighd-vscode clients, where it was ignored anyways
- introcudes a try-catch in the text size estimation switch between STW and AWT, where the SWT check could throw and not fall back on AWT metrics instead.
=> Make Language Server more robust against problems with SWT

build/de.cau.cs.kieler.klighd.repository/category.xml, build/de.cau.cs.kieler.klighd.repository/pom.xml, build/de.cau.cs.kieler.klighd.targetplatform/de.cau.cs.kieler.klighd.targetplatform-piccolo.target, build/de.cau.cs.kieler.klighd.targetplatform/de.cau.cs.kieler.klighd.targetplatform.target, plugins/de.cau.cs.kieler.klighd/META-INF/services/org.eclipse.elk.core.data.ILayoutMetaDataProvider, plugins/de.cau.cs.kieler.klighd/plugin.xml, pom.xml
Updates the build process to now use ELK 0.8.1. Replaces the removed layoutProviders extension point for the KlighdOptions with the service loader counterpart.
=> build: update to ELK 0.8.1

plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/KlighdSetup.java
Blacklists the label manager and the grid placement util properties, as they are currently not useful to the client.
=> adds some properties to the blacklist that are not useful to the client

plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/KlighdSWTGraphicsImpl.java
The previous implementation held the ImageData and Image objects of all images ever used in Klighd in memory. This PR replaces the hard cache with a more memory-sensitive variant using weak references for ImageData and soft references for Image.
=> Implemented memory-sensitive cache for images

plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/KlighdSWTGraphicsImpl.java
This fixes two causes of exceptions that may be thrown because of
undisposed resources and follows the SWT API for these classes,
requesting to be disposed explicitly.
=> piccolo: dispose SWT transform and pattern on dispose.

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramUpdater.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphLanguageServerExtension.xtend
Avoids exceptions caused by broken references in instantiated syntheses
=> lsp: added more synchronization while accessing the view context and syntheses.

plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/filtering/parser/SemanticFilterRuleParserUtil.java
Implemented static `parse()` and `tryParse()`, the latter returns `null` instead of throwing an exception if the syntax is invalid.
Variants with rule names are supported as well.
=> Wrote a util for parsing semantic filter rules

plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/printing/dialog/ActionsBlock.java, plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/printing/dialog/AlignmentBlock.java, plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/printing/dialog/CopiesBlock.java, plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/printing/dialog/KlighdPrintDialog.java, plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/printing/dialog/OrientationBlock.java, plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/printing/dialog/PrintPreviewTray.java, plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/printing/dialog/PrinterBlock.java, plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/printing/dialog/RangeBlock.java, plugins/de.cau.cs.kieler.klighd.ui/src/de/cau/cs/kieler/klighd/ui/printing/dialog/ScalingBlock.java
This PR is split in two commits and has the goal to first simplify the classes in `de.cau.cs.kieler.klighd.ui.printing.dialog` and to replace the deprecated class `org.eclipse.jface.databinding.swt.WidgetProperties`, which is eventually removed in the Eclipse 2022-12 release.
The first commit addresses the first topic and the second one the second.
Please let me know if you prefer more fine grained PRs.
Edit: The deletion is done in https://github.com/eclipse-platform/eclipse.platform.ui/commit/c44f8d77f42cbcc17a0da3daabbb16bcd8745a86
=> Replace deprecated WidgetProperties and simplify klighd.ui.printing.dialog

plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/microlayout/PlacementUtil.java
Previously insets were calculated wrong by offsetting all insets too much when renderings were inside renderigns with offsets. For the server this is an invisible fix, as all Piccolo-related rendering code do not directly use these insets, LSP rendering however directly use the insets for Sprotty, which are now fixed.
=> klighd: fixed inset calculation.

plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/internal/macrolayout/KlighdDiagramLayoutConnector.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/util/KlighdProperties.java
This property automatically creates a padding so that a node's content will fit into the bounds of a rounded rectangle. Can be used when using rounded rectangle renderings to automatically create the required minimal padding.
=> Add property to automatically set minimal paddings for rounded rectangles

plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/internal/macrolayout/KlighdDiagramLayoutConnector.java
See https://github.com/kieler/KLighD/commit/f613c1758bdc05c4461e4a2cc47dee0cb8556416
This line was removed thinking it was not needed in #165, but in fact it was needed. Reverting this to its working previous state.
=> klighd: "Fixed" broken ChildArea Placement

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/RenderingPreparer.xtend, plugins/de.cau.cs.kieler.klighd.piccolo.draw2d/src/de/cau/cs/kieler/klighd/piccolo/draw2d/Draw2DConnectionNode.java, pom.xml
Fixes the build when using newer Java versions. Fixes an issue arising when building the Maven+Plugin modules in Eclipse so that the m2e Tycho and Eclipse builders don't interfere.
=> Fixed build/Eclipse handling

plugins/de.cau.cs.kieler.klighd.incremental/src/de/cau/cs/kieler/klighd/incremental/diff/KComparison.java, plugins/de.cau.cs.kieler.klighd.incremental/src/de/cau/cs/kieler/klighd/incremental/merge/KGraphMerger.java, plugins/de.cau.cs.kieler.klighd.incremental/src/de/cau/cs/kieler/klighd/incremental/util/UIDAdapter.java, plugins/de.cau.cs.kieler.klighd.incremental/src/de/cau/cs/kieler/klighd/incremental/util/UIDAdapters.java, test/de.cau.cs.kieler.klighd.test/src/de/cau/cs/kieler/klighd/test/IncrementalUpdateTest.java
Previously incremental update could run into an issue, where edges were not correctly connected to their target if said target was new. In that case the edge would sometimes be handled before the target resulting in edges connecting to wrong things. This fixes the problem by handling edges only after everything else has been updated.
To reproduce the original issue you can use the below minimal example SCChart and toggle the option induced dataflow: all on and off. The diagram is only drawn correctly after triggering a new synthesis.
```
scchart ports {
region R:
input bool A
initial state s
if A go to s
}
```
=> fix handling of edges by incremental update

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphLayoutEngine.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/KGraphElementIDGenerator.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/RenderingPreparer.xtend
improved ID generation to be consistent between syntheses, yet unique. With this, the LSP does not need to be run with the incremental update strategy anymore to show animations.
Requires the changes from kieler/klighd-vscode#152
=> lsp: improved ID generation to be consistent between syntheses

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/interactive/layered/LayeredInteractiveLanguageServerExtension.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/interactive/rectpacking/RectpackingInteractiveLanguageServerExtension.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/LazyTraceProvider.xtend, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/KlighdSetup.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/ViewContext.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/internal/macrolayout/KlighdLayoutConfigurationStore.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/internal/util/KlighdInternalProperties.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/internal/util/SourceModelTrackingAdapter.java, test/de.cau.cs.kieler.klighd.test/src/de/cau/cs/kieler/klighd/test/IncrementalUpdateTest.java, test/de.cau.cs.kieler.klighd.test/src/de/cau/cs/kieler/klighd/test/ViewContextSourceModelTrackingTest.java
This typo was bugging me for quite some time, now it is no longer. To not break the API of any dependent projects, the old property is still kept as a deprecated property, pointing to the same object as the new one. This leaves us the option to replace the property entirely in some future release.
=> Deprecated and replace the miss-spelled MODEL_ELEMEMT internal property 

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramServer.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphLayoutEngine.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/model/Actions.xtend
The update to Sprotty 1.1.1 brought its injection framework up to the new javax->jakarta change, thus making the re-injections obsolete. Furthermore, remove older FIXMEs that are resolved as the UpdateModelAction contains a cause for some time now.
=> Remove Code Obsolete after Sprotty Update

plugins/de.cau.cs.kieler.klighd.kgraph/src/de/cau/cs/kieler/klighd/kgraph/util/KGraphDataUtil.java
when parsing layout options from persistent entries back to properties, some object valued options cannot be parsed and will throw IllegalStateExceptions, which are not caught anywhere. Non-parsable properties are now just skipped without erroring.
=> kgraph: skip parsing unparsable layout options

plugins/de.cau.cs.kieler.klighd.krendering.extensions/META-INF/MANIFEST.MF
the same dependency to jakarta.inject from de.cau.cs.kieler.klighd cannot be removed, as com.google.inject does not re-export that dependency, requiring either a package import or this direct dependency.
=> krendering.extensions: remove non-direct dependency to jakarta.inject

.github/workflows/buildAndTest.yml
On release branches, look up the `klighd` instead of the `klighd-snapshots` for the Maven repository.
Fixes #163
=> Fix GH Actions builds on release branches

plugins/de.cau.cs.kieler.klighd.lsp/pom.xml
While making LSP a plain maven artifact, it lost its previous configuration to add sources. This adds it back in.
=> lsp: create source jar in build

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/RenderingPreparer.xtend
When generating the SGraph for a KGraph, the SGraph will only be created for any expanded elements and does not recurse further into non-expanded elements. Previously, during the micro layout calculation in the LSP, this still recursed through non-expanded elements, generating IDs for them (resulting in null-IDs) and potentially causing issues and exceptions further down. This fixes the issue by not recursing through the elements either during micro layout, if they are not expanded.
=> lsp: fix an issue when recursing through non-expanded nodes in the micro layout calculation.

plugins/de.cau.cs.kieler.klighd.lsp/pom.xml, pom.xml
In the last 3.0.1 release, the .lsp module does not include the META-INF/services folder anymore, thus not including important configuration of the new interactive and the top-down layout features. This PR configures the maven build to always include that folder for any module that is not a plugin as well (so the .lsp module).
=> lsp: include the META-INF/services folder in maven artifacts.

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphLayoutEngine.xtend
Usually when exporting the graph with Sprotty, we just export the entire graph as-is. ELK has a default value for its padding of 12 pixels, which is also applied to the outermost invisible graph node, shifting all elements inwards by these 12 pixels.
This fix avoids that issue by removing the outermost padding before the layout on any graph, as that would be invisible anyways. With this, exported graphs will always be snug around the outermost graph elements.
Fixes kieler/klighd-vscode#46.
=> lsp: remove outermost padding to remove border when exporting SVGs.

plugins/de.cau.cs.kieler.kgraph.text/src-gen/de/cau/cs/kieler/kgraph/text/services/GRandomGrammarAccess.java, plugins/de.cau.cs.kieler.kgraph.text/src-gen/de/cau/cs/kieler/kgraph/text/services/KGraphGrammarAccess.java, plugins/de.cau.cs.kieler.klighd.kgraph/src/de/cau/cs/kieler/klighd/kgraph/util/KGraphUtil.java, plugins/de.cau.cs.kieler.klighd.krendering/src-custom/de/cau/cs/kieler/klighd/krendering/KRenderingOptions.java, plugins/de.cau.cs.kieler.klighd.krendering/src/de/cau/cs/kieler/klighd/krendering/impl/KRenderingImpl.java, plugins/de.cau.cs.kieler.klighd.krendering/src/de/cau/cs/kieler/klighd/krendering/impl/KRenderingPackageImpl.java, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramGenerator.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramServer.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/gson_utils/EObjectSerializer.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/model/Actions.xtend, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/internal/ILayoutRecorder.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/labels/management/LabelManagementUtil.java
Run the 'Organize imports' action on each class that has unused imports.
On some classes the re-order also existing and used imports. Do you have specific settings for the order of import statements (e.g. in Eclipse preferences: Java -> Code Style -> Organize Imports)? I just used the default settings for this. Please let me know if I should change them.
=> Remove unused imports in Java and xtend classes

plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/internal/macrolayout/KlighdDiagramLayoutConnector.java
instead, only on modified ones.
The label management also has the MANAGED_UNMODIFIED result, which should also not cause the label to be overwritten by the (unmodified) result. Only the MANAGED_MODIFIED should overwrite the label's text and tooltip.
=> fix: do not override label text on unmodified labels

plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/export/AbstractDiagramExporter.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/util/Iterables2.java
This change is based on the assumption that the class Iterables2 is considered an internal helper and not a user facing API.
If that assumption is wrong, this change would indeed breaking change for users.
=> Remove unused or obsolete methods from Iterables2

build/de.cau.cs.kieler.klighd.repository/.settings/org.eclipse.core.resources.prefs, features/de.cau.cs.kieler.klighd.batik.feature/.settings/org.eclipse.core.resources.prefs, features/de.cau.cs.kieler.klighd.draw2d.feature/.settings/org.eclipse.core.resources.prefs, features/de.cau.cs.kieler.klighd.feature/.settings/org.eclipse.core.resources.prefs, features/de.cau.cs.kieler.klighd.freehep.feature/.settings/org.eclipse.core.resources.prefs, features/de.cau.cs.kieler.klighd.ide.feature/.settings/org.eclipse.core.resources.prefs, features/de.cau.cs.kieler.klighd.sdk.feature/.settings/org.eclipse.core.resources.prefs, features/de.cau.cs.kieler.klighd.view.feature/.settings/org.eclipse.core.resources.prefs, plugins-dev/de.cau.cs.kieler.klighd.kgx/.settings/org.eclipse.core.resources.prefs, plugins-dev/de.cau.cs.kieler.klighd.offscreen.application/.settings/org.eclipse.core.resources.prefs, plugins/de.cau.cs.kieler.klighd.piccolo.batik/.settings/org.eclipse.core.resources.prefs, plugins/de.cau.cs.kieler.klighd.piccolo.draw2d/.settings/org.eclipse.core.resources.prefs, plugins/de.cau.cs.kieler.klighd.ui.contrib3x/.settings/org.eclipse.core.resources.prefs, plugins/de.cau.cs.kieler.klighd.ui.emf/.settings/org.eclipse.core.resources.prefs, plugins/de.cau.cs.kieler.klighd.ui.view/.settings/org.eclipse.core.resources.prefs, plugins/de.cau.cs.kieler.klighd.ui.wizard/.settings/org.eclipse.core.resources.prefs, plugins/de.cau.cs.kieler.klighd.ui/.settings/org.eclipse.core.resources.prefs, test/de.cau.cs.kieler.klighd.piccolo.test/.settings/org.eclipse.core.resources.prefs, test/de.cau.cs.kieler.klighd.test/.settings/org.eclipse.core.resources.prefs
Without an explicit encoding a warning is created: 'Project XYZ has no explicit encoding'
=> Set encoding of remaining project to UTF-8 explicitly to fix warnings

pom.xml
Using the --release option instead --source plus --target is more convenient (just one option) and more powerful (checks also that now newer Java API is used even if the executing JDK is newer).
=> [Build] Set Java Compiler's -release option instead of -source + -target

pom.xml
Reverts kieler/KLighD#214
Seems like the PR #214 did lead to errors not occuring in the PR build due to Javadoc building:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:jar (attach-javadocs) on project de.cau.cs.kieler.klighd.kgraph: MavenReportException: Error while generating Javadoc: 
Error:  Exit code: 1
Error: [ERROR] error: module org.eclipse.emf.ecore.xmi reads package org.eclipse.core.runtime from both org.eclipse.equinox.common and org.eclipse.equinox.registry
Error: [ERROR] error: module org.eclipse.emf.ecore.xmi reads package org.eclipse.core.internal.runtime from both org.eclipse.equinox.common and org.eclipse.core.runtime
Error: [ERROR] error: module org.eclipse.emf.ecore.xmi reads package org.eclipse.core.runtime from both …
```
=> Revert "[Build] Set Java Compiler's -release option instead of -source + -target"

plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramGenerator.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramServer.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphDiagramUpdater.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphLayoutEngine.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/model/Actions.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/model/KGraphModel.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/KGraphMappingUtil.xtend, plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/RenderingPreparer.xtend
=> copy properties to the SModel already during initial SModel generation

pom.xml
In the most recent versions of Maven these warnings are now errors
=> [Build] Fix build plugin version warnings

plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/KlighdCanvas.java
This PR turns around the call of setBounds(Rectangle) to setBounds(int, int, int, int) that worked until Eclipse 2024-12 so that now setBounds(int, int, int, int) calls setBounds(Rectangle) with the same behavior, to match the API change of the Canvas class in Eclipse 2025-03.
This should fix #225 and not break the behavior in previous editions.
=> Turn around setBounds calls in KLighDCancas to avoid a circular call from Eclipse 2025-03.

plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/internal/macrolayout/KlighdDiagramLayoutConnector.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/labels/management/SoftWrappingLabelManager.java, plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/util/KlighdProperties.java
Add a property that should be set on Labels and expand the softwrapping label manager to fuzzily check whether the next line could be placed on the current line.
This reduces wasted whitespace.
=> Add fuzziness to softwrapping label manager.
